# -*- coding: utf-8 -*-
{
    'name': 'Control Interno',
    'version': '1.0',
    'category': 'Operations',
    'summary': 'Internal Control Management System',
    'description': """
        Internal Control Management System
    """,
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'depends': ['base', 'mail', 'survey', 'board', 'hr', 'export_view_pdf'],
    'data': [
        # 'security/security.xml',
        'security/internal_control_groups.xml',
        'security/ir.model.access.csv',
        'security/internal_control_record_rules.xml',
        'data/email_templates.xml',
        'data/mail_template.xml',
        'data/mail_message_subtype.xml',
        'data/ir_cron_data.xml',
        'views/survey_user_input_report.xml',
        'views/survey_views_department.xml',
        'views/survey_views.xml',
        'views/survey_menu.xml',
        'views/survey_activity_views.xml',
        'views/survey_question_upload_views.xml',
        'views/survey_user_input_line_upload_views.xml',
        'views/survey_templates_upload.xml',
        'reports/survey_base_template.xml',
        'reports/survey_reports.xml',
        'reports/survey_revised_items_template.xml',
        'reports/survey_compliance_template.xml',
        'reports/survey_compliance_campaign_template.xml',
        'reports/survey_revised_items_campaign_template.xml',
        'reports/survey_satisfaction_campaign_template.xml',
        'reports/survey_participation_campaign_template.xml',
        'reports/survey_compliance_summary_template.xml',
        'reports/survey_satisfaction_template.xml',
        'reports/survey_participation_template.xml',
        'reports/survey_export_templates.xml',
        'views/survey_campaign_views.xml',
        'views/in_survey_survey_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'internal_control/static/src/css/hide_survey_share_invite.css',
            'internal_control/static/src/js/survey_export_dialog.js',
            'internal_control/static/src/js/survey_pdf_export.js',
            'internal_control/static/src/xml/survey_export_dialog.xml',
            'internal_control/static/src/xml/survey_pdf_dropdown.xml',
        ],
        'web.assets_frontend': [
            'internal_control/static/src/js/survey_section_single.js',
            'internal_control/static/src/js/survey_form_mock.js',
            'internal_control/static/src/css/hide_survey_share_invite.css',
            'internal_control/static/src/css/survey_custom.css',
            'internal_control/static/src/css/survey_upload.css',
            # 'internal_control/static/src/js/survey_form_attachment.js',
            # 'internal_control/static/src/js/survey_form_widget.js',
        ],
        'web.assets_qweb': [
            'internal_control/static/src/js/survey_section_single.js',
            'internal_control/static/src/css/survey_custom.css',
        ],
        'website.assets_frontend': [
            'internal_control/static/src/js/survey_section_single.js',
            'internal_control/static/src/css/survey_custom.css',
            'internal_control/static/src/css/survey_upload.css',
            # 'internal_control/static/src/js/survey_form_attachment.js',
            # 'internal_control/static/src/js/survey_form_widget.js',
        ],
        'survey.survey_assets': [
            'internal_control/static/src/js/survey_form_attachment.js',
            # 'internal_control/static/src/js/survey_form_widget.js',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
} 