from . import whatsapp_templates
from . import whatsapp_template_call_to_action
from . import whatsapp_instance
from . import whatsapp_messages
from . import res_users
from . import res_company
from . import terminal_log
from . import res_partner
from . import whatsapp_chatbot
from . import sale_order
from . import whatsapp_messages_user
from . import response_wenhook_chatbot
from . import whatsapp_quick_reply
from . import pos_config