# -*- coding: utf-8 -*-
{
    'name': 'EC Recursos Humanos',
    'version': '17.0.1.0.0',
    'author': '',
    'category': 'Recursos Humanos',
    'sequence': 10,
    'description': "",

    'images': [
    ],
    'depends': [
        'base',
        'account',
        'account_accountant',
        'hr',
        'hr_contract',
        'hr_holidays',
        'hr_attendance',
        'hr_payroll',
        'hr_payroll_account',
        'analytic',
        'hr_work_entry_contract_enterprise'
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/groups.xml',
        'data/employee_to_notify.xml',
        'data/rules_data.xml',
        'data/mail_template.xml',
        # 'data/hide_rules_data.xml',
        # 'data/expense_paperformat.xml',
        # 'data/request_overtime_data.xml',
        # 'data/egress_request_data.xml',
        # 'data/role_paperformat.xml',
        # 'data/request_overtime_paperformat.xml',
        # 'data/contract_data.xml',
        # 'data/hr_liquidation_data.xml',
        # 'data/contract_finish_mail.xml',
        # 'views/root_menu.xml',
        # 'views/analisis_lineas_nomina_view.xml',
        'views/employee_view.xml',
        # 'views/payment_view.xml',
        'views/contract_view.xml',
        'views/rule_view.xml',
        # 'views/structure_view.xml',
        # 'views/scheduled_transaction_view.xml',
        'views/slip_view.xml',
        # 'views/batch_slip_view.xml',
        # 'views/res_config.xml',
        # 'views/impuesto_renta_view.xml',
        'views/family_burden_view.xml',
        # 'views/request_overtime_view.xml',
        # 'views/request_egress_view.xml',
        # 'views/request_loan_payment_view.xml',
        # 'views/company_view.xml',
        # 'views/vacations_view.xml',
        'views/subsidy_view.xml',
        # 'views/hr_liquidation_view.xml',
        # 'views/generate_filebb_wizard.xml',
        # 'views/department_view.xml',
        'views/hr_recruiment_view.xml',
        'views/provision_view.xml',
        'views/job_view.xml',
        'views/hr_departure_wizard_view.xml',
        'views/block_camps_model_view.xml',
        'views/settings_employee_view.xml',
        # 'views/hr_payment_view.xml',
        # 'views/res_config.xml',
    ],
    'qweb': [
    ],
    'demo': [
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
