from . import hr_employee
from . import hr_departament
from . import stock_warehouse
from . import pos_config
from . import stock_lot
from . import stock_move_line
from . import stock_move
from . import stock_picking
from . import stock_return_picking
from . import res_config_settings
from . import res_users